# Generated by Django 4.2.4 on 2023-08-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classroom", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("second_name", models.CharField(max_length=25)),
                ("phone_number", models.IntegerField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gym_manager_api.user",
                    ),
                ),
                ("role", models.CharField(default="instructor", max_length=25)),
            ],
            bases=("gym_manager_api.user",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gym_manager_api.user",
                    ),
                ),
                ("role", models.CharField(default="student", max_length=25)),
            ],
            bases=("gym_manager_api.user",),
        ),
        migrations.CreateModel(
            name="Scheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateTimeField(blank=True, null=True)),
                ("hour", models.DateTimeField(blank=True, null=True)),
                ("classroom", models.ManyToManyField(to="gym_manager_api.classroom")),
                ("instructor", models.ManyToManyField(to="gym_manager_api.instructor")),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("whereabouts", models.ManyToManyField(to="gym_manager_api.scheduler")),
                ("studens", models.ManyToManyField(to="gym_manager_api.student")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("group", models.ManyToManyField(to="gym_manager_api.group")),
                ("instructor", models.ManyToManyField(to="gym_manager_api.instructor")),
                ("students", models.ManyToManyField(to="gym_manager_api.student")),
            ],
        ),
    ]
