# Generated by Django 4.2.6 on 2023-10-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='whereabouts',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whereabouts', to='gym_manager_api.group'),
        ),
    ]
