# Generated by Django 4.2.4 on 2023-08-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym_manager_api", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduler",
            old_name="day",
            new_name="time",
        ),
        migrations.RemoveField(
            model_name="scheduler",
            name="hour",
        ),
    ]
