# Generated by Django 4.2.6 on 2023-10-15 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0002_remove_group_whereabouts_scheduler_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hour',
            field=models.TimeField(default=datetime.time(10, 30)),
        ),
    ]
