# Generated by Django 4.2.4 on 2023-08-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym_manager_api", "0003_rename_day_scheduler_time_remove_scheduler_hour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="studens",
            new_name="students",
        ),
    ]
