# Generated by Django 4.2.4 on 2023-08-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym_manager_api", "0005_rename_students_event_attendees"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="classroom",
            new_name="name",
        ),
    ]
