# Generated by Django 4.2.4 on 2023-08-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_manager_api", "0006_rename_classroom_classroom_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
