# Generated by Django 4.2.4 on 2023-08-13 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_manager_api", "0008_alter_user_phone_number_eventexception"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduler",
            name="time",
        ),
        migrations.AddField(
            model_name="scheduler",
            name="first",
            field=models.DateField(
                default=datetime.datetime(2023, 8, 13, 20, 4, 8, 373813)
            ),
        ),
        migrations.AddField(
            model_name="scheduler",
            name="hour",
            field=models.TimeField(default=datetime.time(10, 30)),
        ),
        migrations.AddField(
            model_name="scheduler",
            name="last",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduler",
            name="repeat_on",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THR", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                    ("SUN", "Sunday"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventexception",
            name="move_from",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 13, 20, 4, 8, 376358)
            ),
        ),
        migrations.AlterField(
            model_name="eventexception",
            name="move_to",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 13, 20, 4, 8, 376367)
            ),
        ),
    ]
