# Generated by Django 4.2.6 on 2023-10-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0009_remove_event_duration_event_classroom_event_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='instructor',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_manager_api.classroom'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_manager_api.instructor'),
        ),
    ]
