# Generated by Django 4.2.4 on 2023-08-13 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gym_manager_api",
            "0009_remove_scheduler_time_scheduler_first_scheduler_hour_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventexception",
            name="move_from",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 13, 20, 57, 33, 668989)
            ),
        ),
        migrations.AlterField(
            model_name="eventexception",
            name="move_to",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 13, 20, 57, 33, 668998)
            ),
        ),
        migrations.AlterField(
            model_name="scheduler",
            name="first",
            field=models.DateField(
                default=datetime.datetime(2023, 8, 13, 20, 57, 33, 666475)
            ),
        ),
    ]
