# Generated by Django 4.2.4 on 2023-08-13 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gym_manager_api", "0010_alter_eventexception_move_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventexception",
            name="move_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="eventexception",
            name="move_to",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="scheduler",
            name="first",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
