# Generated by Django 4.2.6 on 2023-12-16 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0013_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='scheduler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='gym_manager_api.scheduler'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='gym_manager_api.group'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='gym_manager_api.student'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'scheduler', 'student'), name='unique_attendance'),
        ),
    ]
