# Generated by Django 4.2.6 on 2023-12-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0014_attendance_scheduler_alter_attendance_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='state',
            field=models.CharField(blank=True, choices=[('PAI', 'paid'), ('UNP', 'unpaid'), ('PPR', 'paid present'), ('UPR', 'unpaid present'), ('UNP', 'unpaid not present'), ('PNP', 'paid not present')], default='UNP', max_length=3, null=True),
        ),
    ]
