# Generated by Django 4.2.6 on 2023-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0016_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='entrances_left',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
