# Generated by Django 4.2.6 on 2023-12-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0017_alter_subscription_entrances_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='entrances_left',
            field=models.IntegerField(),
        ),
    ]
