# Generated by Django 4.2.6 on 2023-12-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0020_alter_subscription_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
