# Generated by Django 4.2.6 on 2023-12-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0022_remove_subscription_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='valid_since',
            new_name='valid_start',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='valid_until',
            new_name='valid_stop',
        ),
    ]
