# Generated by Django 4.2.6 on 2023-12-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager_api', '0023_rename_valid_since_subscription_valid_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='state',
            field=models.CharField(blank=True, choices=[('PRE', 'present'), ('ABS', 'absent')], max_length=3, null=True),
        ),
    ]
